# Generated by Django 5.1.7 on 2025-03-08 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=100, unique=True)),
                ('published_at', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('page_count', models.IntegerField()),
                ('language', models.CharField(max_length=100)),
                ('authors', models.ManyToManyField(related_name='books', to='authors.author')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.genre')),
            ],
        ),
    ]
