# Generated by Django 5.1.7 on 2025-03-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_title_bookcopy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcopy',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
