# Generated by Django 5.1.7 on 2025-03-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_booklending'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookcopy',
            options={'verbose_name': 'Book Copy', 'verbose_name_plural': 'Book Copies'},
        ),
        migrations.AlterField(
            model_name='booklending',
            name='returned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
